### ISSUE TITLE
Dask HyperbandSearchCV and Keras Metrics crashes

### ISSUE THREAD

**Issue by sim-san** [adriangb/scikeras#34] opened 2020-08-04 08:43 UTC
Hi Adrian,
There is also a problem with the keras metrics and the HyperbandSearchCV  from dask-ml. I think this happens because there are no metrics in history on the first _warm_start_ .

<details><summary>Code:</summary>

```python
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Flatten
from scikeras.wrappers import KerasRegressor

import numpy as np
from dask.distributed import Client, LocalCluster

import dask_ml.model_selection as dcv


def model_building_function(X, n_outputs_, hidden_layer_sizes, activation_func):
    """Dynamically build regressor."""

    model = Sequential()
    model.add(Flatten(input_shape=X.shape[1:]))
    for size in hidden_layer_sizes:
        model.add(Dense(size, activation=activation_func))
    model.add(Dense(n_outputs_))
    model.compile("adam", loss="mean_squared_error",
                  metrics=['mse', 'mae', 'logcosh']
                  )
    return model


class Est(KerasRegressor):
    def __init__(self, hidden_layer_sizes=None, activation_func=None):
        self.hidden_layer_sizes = hidden_layer_sizes
        self.activation_func = activation_func
        super().__init__()

    """
    def __call__(self, X, n_outputs_, hidden_layer_sizes, activation_func):
        model = model_building_function(
            X, n_outputs_, hidden_layer_sizes, activation_func
        )
        return model

    """
    def __call__(self, X, n_outputs_, hidden_layer_sizes, activation_func):
        print('Est args:', X, n_outputs_, hidden_layer_sizes, activation_func)

        model = model_building_function(
            X, n_outputs_, hidden_layer_sizes, activation_func
        )
        return model



if __name__ == "__main__":
    cluster = LocalCluster(processes=True, n_workers=5, threads_per_worker=1)
    # cluster = LocalCluster(processes=False, n_workers=1, threads_per_worker=1)

    dask_client = Client(cluster)
    #dask_client = Client('localhost:8786', timeout=10)



    model = KerasRegressor( build_fn=model_building_function,
                            hidden_layer_sizes=[32, 32], activation_func="relu")

    #model = Est(hidden_layer_sizes=[32, 32], activation_func="relu")
    #model = KerasRegressor(build_fn=Est(), hidden_layer_sizes=[32, 32], activation_func="relu")

    # generate data
    X = np.arange(1.0, 5001.0).reshape((100, 50)).astype(np.float32)
    y = np.arange(1.0, 101.0).reshape(100, 1).astype(np.float32)

    # specify parameters and distributions to sample from
    param_dist = {
        "hidden_layer_sizes": [[16, 16], [32, 32], [64, 64], [128, 128], [256, 256]],
        "activation_func": ["relu", "elu"],
    }

    hyperband = dcv.HyperbandSearchCV(model, param_dist, max_iter=12, aggressiveness=3,verbose=True)

    print("START HyperbandSearchCV")
    hyperband.fit(X, y)
    print("best score =", hyperband.best_score_)
    assert hasattr(hyperband, "best_score_")
```

</details>

<details><summary>Traceback</summary>
<p>

```
Traceback (most recent call last):
  File "D:\...\site-packages\distributed\utils.py", line 665, in log_errors
    yield
  File "D:\...\lib\site-packages\dask_ml\model_selection\_incremental.py", line 102, in _partial_fit
    model.partial_fit(X, y, **(fit_params or {}))
  File "D:\...\lib\site-packages\scikeras\wrappers.py", line 577, in partial_fit
    X, y, sample_weight=sample_weight, warm_start=True, **kwargs
  File "D:\...\lib\site-packages\scikeras\wrappers.py", line 548, in fit
    X, y, sample_weight=sample_weight, warm_start=warm_start, **kwargs
  File "D:\...\lib\site-packages\scikeras\wrappers.py", line 330, in _fit_keras_model
    k: self.history_[k] + hist.history[k] for k in keys
  File "D:\...\site-packages\scikeras\wrappers.py", line 330, in <dictcomp>
    k: self.history_[k] + hist.history[k] for k in keys
KeyError: 'log_cosh'
```

</p>
</details>

**Comment by adriangb** [comment] 2020-08-04 14:06
I was able to reproduce, thank you for the clean example. I will look into resolving this.

**Comment by adriangb** [comment] 2020-08-06 13:41
So this is partly due to a TF bug: https://github.com/tensorflow/tensorflow/pull/42097

**Closed** 2020-08-10 16:42 UTC
